"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
"source ~/.vim/dotvim.vim

"if has("user_commands")
"  set nocompatible
"  filetype off
"  set rtp+=~/.vim/bundle/vundle/
"  call vundle#rc()
"  "let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'ruby', 'python', 'misc']
"  let g:vundles=['general', 'programming']
"  let g:neocomplcache_enable_at_startup = 1
"  " Load 'vundles'
"  source ~/.vim/vundles.vim
"  " Add extra bundles here...
"  " Bundle 'reponame'
"endif

" Customize to your needs...

" for iterm2 color
set term=xterm-256color

" Turn on syntax highlighting
syntax on

" enables filetype detection for purposes of plugins and indenting
filetype plugin indent on

" Golang config
autocmd FileType go setlocal tabstop=4 noexpandtab

" Avoid E363
set mmp=5000

