#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Sets dotzsh options.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# debug: see with `dzinfo`
##zstyle ':dotzsh:load' timing 'yes'
##zstyle ':dotzsh:module:*' timing 'yes'

# Set the Zsh modules to load (man zshmodules).
zstyle ':dotzsh:load' zmodule 'stat'

# Set the Zsh functions to load (man zshcontrib).
zstyle ':dotzsh:load' zfunction 'zargs' 'zmv'

# Set the dotzsh modules to load (browse modules).
# The order matters.
zstyle ':dotzsh:load' dzmodule \
  'gnu-utility' \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'utility' \
  'completion' \
  'theme'

### Global settings
# Color output (auto set to 'no' on dumb terminals).
zstyle ':dotzsh:module:*' color 'yes'
# Setup aliases for modules (disable per module below).
zstyle ':dotzsh:module:*' aliases 'yes'
# Set case-sensitivity for completion, history lookup, etc.
zstyle ':dotzsh:module:*' case-sensitive 'no'

### Environment module
# Set which PAGER to use less or more
##zstyle ':dotzsh:module:environment' pager 'less'
# Enable mouse scrolling in less, add the following to *zshrc*
##zstyle ':dotzsh:module:environment:pager:less' mousescroll 'false'

### Terminal Module
# Auto set the tab and window titles.
zstyle ':dotzsh:module:terminal' auto-title 'yes'

### Editor module
# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' keymap 'emacs'
# Set EDITOR to 'emacs' or 'vi'.
zstyle ':dotzsh:module:editor' editor 'vi'
# Auto convert .... to ../..
#zstyle ':dotzsh:module:editor' dot-expansion 'yes'

### Utility Module
# Disable `diff` highlighting
##zstyle ':dotzsh:module:utility:diff' color 'no'
# Disable `wdiff` highlighting
##zstyle ':dotzsh:module:utility:wdiff' color 'no'
# Disable `make` highlighting
##zstyle ':dotzsh:module:utility:make' color 'no'

### Completion module
# Expand global aliases automatically
#zstyle ':dotzsh:module:completion' expand-global-aliases 'yes'

### SSH module
zstyle ':dotzsh:module:ssh:agent' forwarding 'yes'
#zstyle ':dotzsh:module:ssh:aliases' hosts 'yes'
##zstyle ':dotzsh:module:ssh:agent' identities 'id_rsa' 'id_rsa2' 'id_github'

### GNUPG module
# Enable ssh-agent protocol emulation for gpg-agent
##zstyle ':dotzsh:module:gnupg' agent-ssh-support 'yes'

### OSX module
# Add aliases for Applications
##zstyle ':dotzsh:module:osx' launcher 'yes'
# Open/Resume temrinal in correct dir
##zstyle ':dotzsh:module:osx' terminal-resume 'yes'

### Git module
# Disable all git aliases
##zstyle ':dotzsh:module:git' aliases 'no'

### TMUX module
# Auto start a session when Zsh is launched.
# Setting it to 'local' only starts a session for local terminals.
# Setting it to 'remote' only starts a session for SSH connections.
##zstyle ':dotzsh:module:tmux' auto-start 'no'
#zstyle ':dotzsh:module:tmux:aliases' tmuxinator 'yes'

### Syntax Highlighting module
#zstyle ':dotzsh:module:syntax-highlighting' highlighters 'main' 'brackets' 'pattern' \
#  'cursor' 'root' \

### Theme module
# Set default theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
zstyle ':dotzsh:module:theme' theme 'dotphiles'
### Set custom theme based on hostname or domain
# zstyle ':dotzsh:module:theme:hostname:your-host-here' theme 'dotphiles' 'soldark' 'magenta'
# zstyle ':dotzsh:module:theme:hostname:your-other-host-here' theme 'dotphiles' 'soldark' 'violet'
# zstyle ':dotzsh:module:theme:domain:your-domain-here' theme 'dotphiles' 'soldark' 'orange'

### Load dotzsh
source "$DOTZSH/init.zsh"

### Customize to your needs...

## Environment Variables
export GIT_VOLUME="/Volumes/git/src"
export PATH="/usr/bin:/usr/local/bin:$PATH"

## Use vim keybindings in terminal
set -o vi

# With additional bindings that are missing by default
bindkey -v '^?' backward-delete-char
my-backward-delete-word() {
    local WORDCHARS=${WORDCHARS/\//}
    zle backward-delete-word
}
zle -N my-backward-delete-word
bindkey '^W' my-backward-delete-word

## Enable reverse search
bindkey -v
bindkey '^R' history-incremental-search-backward

## Enable git tab completion
autoload -Uz compinit && compinit

# Helpful aliases
alias ll='ls -Gflash'
alias dsl='~/.dotfiles/dotsync/bin/dotsync -L'
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias vi="vim"

# Python development
## Pyenv setup
if test -d "${HOME}/.pyenv"; then
    export PYENV_ROOT="$HOME/.pyenv"
    [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi

## Useful macros
cleanpy() {
    if git diff HEAD --name-only | grep -q .*.py$; then
        for cmd in 'isort' 'black' 'flake8 --ignore E501'; do 
            pipenv run ${cmd} $(git diff HEAD --name-only | grep .*.py$)
        done
    fi
}

# Git helpers
gclone() {
    local repo_url=${1}
    local repo_path="$(echo ${repo_url} | sed -e 's/^https:\/\///' -e 's/^git@//g' -e 's/\.git$//g' -e 's/:/\//g')"
    local domain="$(echo ${repo_path} | cut -d'/' -f1)"
    local repo="$(basename ${repo_path})"
    local org="$(basename $(dirname ${repo_path}))"
    local target=${GIT_VOLUME}/${domain}/${org}/${repo}
    if ! test -d ${target}/.git; then
        git clone "git@${domain}:${org}/${repo}.git" ${target}
    fi
    cd ${target}
}

# Hook for work setup
if test -f ~/.private/zshrc-work; then
    source ~/.private/zshrc-work
fi

# Created by `pipx`
export PATH="$PATH:~/.local/bin"
export JAVA_HOME="$(/usr/libexec/java_home)"

# Necessary for faster tabcompletion on WSL
# May be unnecessary in other environments
# Have not confirmed if this is detrimental in any environments
unsetopt pathdirs
